[package]
name = "stelaro"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[dependencies]
ariadne = "0.5.1"
bumpalo = "3.17.0"

[dev-dependencies]
insta = { version = "1.42.2", features = ["glob"] }

[profile.dev.package]
insta.opt-level = 3
similar.opt-level = 3